[package]
name = "grit-util"
version = "0.1.0"
edition = "2021"

[lints]
rust.unused_crate_dependencies = "warn"

[dependencies]
derive_builder = { version = "0.13.1" }
serde = { version = "1.0.164", features = ["derive"] }
